# Generated by Django 5.2 on 2025-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteerinterest_subscription_subscribed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerinterest',
            name='availability',
        ),
        migrations.AddField(
            model_name='volunteerinterest',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name="Anything else you'd like us to know?"),
        ),
        migrations.AddField(
            model_name='volunteerinterest',
            name='discover',
            field=models.CharField(blank=True, max_length=20, verbose_name='How did you heard about Class Matters?'),
        ),
        migrations.AddField(
            model_name='volunteerinterest',
            name='occupation',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteerinterest',
            name='interest_area',
            field=models.CharField(choices=[('1', '1: CLASSES'), ('2', '2: ESTEAM'), ('3', '3: STEM LIKE ME'), ('4', '4: EARLY STEM VILLAGE'), ('5', '5: SERVICE MATTERS'), ('6', '6: SPARK SUMMER CAMP'), ('7', '7: RECOGNITION MATTERS')], default='1', max_length=10, verbose_name='What pillar are you interested in representing?'),
        ),
    ]
