# Generated by Django 5.2 on 2025-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_volunteerinterest_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.FloatField(default=0, verbose_name='Donation Amount')),
                ('recurring', models.BooleanField(verbose_name='Make this a monthly donation.')),
                ('quick_subscribe', models.BooleanField(verbose_name="I'd like to subscribe now and recieve monthly updates.")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
