# Generated by Django 5.2 on 2025-05-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribed_at',
            new_name='timestamp',
        ),
    ]
